wandb_version: 1

git_commit:
  desc: null
  value: 66cf66713da1063e9da2466810fd66ba7007094b
_wandb:
  desc: null
  value:
    python_version: 3.12.11
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.45.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1756176361
    t:
      1:
      - 1
      - 11
      - 12
      - 30
      - 41
      - 49
      - 51
      - 55
      - 71
      2:
      - 1
      - 11
      - 12
      - 30
      - 41
      - 49
      - 51
      - 55
      - 71
      3:
      - 14
      - 16
      - 23
      - 24
      - 61
      - 62
      4: 3.12.11
      5: 0.17.5
      6: 4.45.2
      8:
      - 5
      13: linux-x86_64
optimizer:
  desc: null
  value:
    learning_rate: 1.0e-05
    weight_decay: 0.0
    min_lr_ratio: 1.0
    warmup_ratio: null
    warmup: 5.0
    stable: 0.0
    cooldown: 0.0
    lr_schedule: cosine
    weight_decay_modules: null
    default_weight_decay_mask: null
    beta1: 0.9
    beta2: 0.95
    epsilon: 1.0e-05
    max_grad_norm: 1.0
trainer:
  desc: null
  value:
    seed: 0
    mp:
      param_dtype: jax.numpy.float32
      compute_dtype: jax.numpy.bfloat16
      output_dtype: jax.numpy.bfloat16
    fp8: null
    wandb:
      entity: null
      project: Expert-Iter
      name: null
      tags: []
      id: Expert_V2_round3
      group: null
      mode: null
      resume: allow
      save_code: true
      save_xla_dumps: false
    log_dir: logs
    run_base_dir: runs
    id: Expert_V2_round3
    tracker:
      entity: null
      project: Expert-Iter
      name: null
      tags: []
      id: Expert_V2_round3
      group: null
      mode: null
      resume: allow
      save_code: true
      save_xla_dumps: false
    profiler: false
    profiler_start_step: 5
    profiler_num_steps: 100
    profiler_perfetto_link: false
    batch_axis: batch
    fsdp_axis: embed
    tensor_parallel_axes:
    - mlp
    - heads
    axis_resources: {}
    parameter_axis_resources: {}
    replica_ici_axis_size: 1
    model_axis_size: 1
    replica_dcn_axis_size: 1
    train_batch_size: 512
    per_device_parallelism: 8
    per_device_eval_parallelism: 8
    num_train_steps: 52
    steps_per_eval: 10
    max_eval_batches: null
    checkpointer:
      base_path: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/checkpoints
      save_interval: '1:00:00'
      keep:
      - every: 10000
    load_checkpoint: null
    load_checkpoint_path: null
    initialize_from: null
    jax_config:
      jax_threefry_partitionable: true
      jax_softmax_custom_jvp: true
    distributed:
      coordinator_address: null
      num_processes: null
      process_id: null
      local_device_ids: null
    ray:
      address: null
      start_workers: true
      auto_start_cluster: true
    require_accelerator: true
    shutdown_at_exit: false
max_tune_length:
  desc: null
  value: 2048
train_data:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/data/train.json
train_data_cache_dir:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/data/train_cache
eval_data:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/data/test.json
eval_data_cache_dir:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/data/test_cache
model_name_or_path:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round2/RL_model
tokenizer_name_or_path:
  desc: null
  value: kfdong/STP_model_Lean_0320
trust_remote_code:
  desc: null
  value: true
model_cache_dir:
  desc: null
  value: null
hf_save_path:
  desc: null
  value: /n/netscratch/amin_lab/Lab/slim/Lean/storage/Expert_V2/round3/hf_checkpoints
save_freq:
  desc: null
  value: 51
