max_tune_length: 2048

model_name_or_path: "AI-MO/Kimina-Prover-Preview-Distill-1.5B"
#"deepseek-ai/DeepSeek-Prover-V1.5-SFT"
tokenizer_name_or_path:  "AI-MO/Kimina-Prover-Preview-Distill-1.5B"
#"deepseek-ai/DeepSeek-Prover-V1.5-SFT"
trust_remote_code: True

trainer:
  tracker:
    type: wandb
    project: "Kimina"
    name: "Kimina-sft"
    tags: ["AI-MO/Kimina-Prover-Preview-Distill-1.5B", "STP"]

  mp: p=f32,c=bfloat16
  load_checkpoint_path : /n/netscratch/amin_lab/Lab/slim/STP/storage/SFT_ckpt/2f5zan35
  train_batch_size: 1024
  num_train_steps: 240
  steps_per_eval: 20

  tensor_parallel_axes: ["mlp", "heads"]
  per_device_eval_parallelism: 16
  per_device_parallelism: 16
save_freq: 240

optimizer:
  learning_rate: 1e-4
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.95
  epsilon: 1E-5
  warmup: 20
  min_lr_ratio: 1.0